// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NihzW-f86FXG0rQ6w2M5xco10cDVNG0',
    appId: '1:34705185628:web:7aee09c1b1e02e39fc3f99',
    messagingSenderId: '34705185628',
    projectId: 'insuremart-d134f',
    authDomain: 'insuremart-d134f.firebaseapp.com',
    storageBucket: 'insuremart-d134f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO14ebL4ObyM2fpiN4LGS93osMMnGytp4',
    appId: '1:34705185628:android:95e8987fffd19bd3fc3f99',
    messagingSenderId: '34705185628',
    projectId: 'insuremart-d134f',
    storageBucket: 'insuremart-d134f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2i7WipGLEEBccmfFZ44qH76V6rIHLRQY',
    appId: '1:34705185628:ios:af84121ff0317f8afc3f99',
    messagingSenderId: '34705185628',
    projectId: 'insuremart-d134f',
    storageBucket: 'insuremart-d134f.firebasestorage.app',
    iosClientId: '34705185628-08gactkfo3n3grtqonnldc9uarcctdkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.insureMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2i7WipGLEEBccmfFZ44qH76V6rIHLRQY',
    appId: '1:34705185628:ios:af84121ff0317f8afc3f99',
    messagingSenderId: '34705185628',
    projectId: 'insuremart-d134f',
    storageBucket: 'insuremart-d134f.firebasestorage.app',
    iosClientId: '34705185628-08gactkfo3n3grtqonnldc9uarcctdkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.insureMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7NihzW-f86FXG0rQ6w2M5xco10cDVNG0',
    appId: '1:34705185628:web:b4b28547bdf0abdffc3f99',
    messagingSenderId: '34705185628',
    projectId: 'insuremart-d134f',
    authDomain: 'insuremart-d134f.firebaseapp.com',
    storageBucket: 'insuremart-d134f.firebasestorage.app',
  );
}
